const countries = {
   Afghanistan: "Afganistan",
   Albania: "Albania",
   Algeria: "Algieria",
   Andorra: "Andora",
   Angola: "Angola",
   Argentina: "Argentyna",
   Armenia: "Armenia",
   Australia: "Australia",
   Austria: "Austria",
   Azerbaijan: "Azerbejdżan",
   Bahrain: "Bahrajn",
   Bangladesh: "Bangladesz",
   Belarus: "Białoruś",
   Belgium: "Belgia",
   Bolivia: "Boliwia",
   'Bosnia and Herzegovina': "Bośnia i Hercegowina",
   Brazil: "Brazylia",
   Bulgaria: "Bułgaria",
   Cambodia: "Kambodża",
   Cameroon: "Kamerun",
   Canada: "Kanada",
   Chad: "Czad",
   Chile: "Chile",
   China: "Chiny",
   Colombia: "Kolumbia",
   CostaRica: "Kostaryka",
   'Congo DR': "Demokratyczna Republika Kongo",
   'Côte d’Ivoire': "Wybrzeże Kości Słoniowej",
   Croatia: "Chorwacja",
   Cuba: "Kuba",
   Cyprus: "Cypr",
   'Czech Republic': "Czechy",
   Denmark: "Dania",
   Dominica: "Dominika",
   'Dominican Republic': "Dominikana",
   Ecuador: "Ekwador",
   Egypt: "Egipt",
   Salvador: "Salwador",
   England: "Anglia",
   Eritrea: "Erytrea",
   Estonia: "Estonia",
   Ethiopia: "Etiopia",
   Fiji: "Fidżi",
   Finland: "Finlandia",
   France: "Francja",
   Gabon: "Gabon",
   Georgia: "Gruzja",
   Germany: "Niemcy",
   Ghana: "Ghana",
   Greece: "Grecja",
   Greenland: "Grenlandia",
   Guatemala: "Gwatemala",
   Guinea: "Gwinea",
   'Guinea-Bissau': "Gwinea Bissau",
   Haiti: "Haiti",
   Honduras: "Honduras",
   Hungary: "Węgry",
   Iceland: "Islandia",
   India: "Indie",
   Indonesia: "Indonezja",
   Iran: "Iran",
   Iraq: "Irak",
   Israel: "Izrael",
   Italy: "Włochy",
   Jamaica: "Jamajka",
   Japan: "Japonia",
   Java: "Jawa",
   Jordan: "Jordania",
   Kazakhstan: "Kazachstan",
   Kenya: "Kenia",
   Kuwait: "Kuwejt",
   Kyrgyzstan: "Kirgistan",
   Laos: "Laos",
   Latvia: "Łotwa",
   Lebanon: "Liban",
   Lesotho: "Lesotho",
   Liberia: "Liberia",
   Libya: "Libia",
   Liechtenstein: "Liechtenstein",
   Lithuania: "Litwa",
   Luxembourg: "Luksemburg",
   Macedonia: "Macedonia",
   Madagascar: "Madagaskar",
   Malawi: "Malawi",
   Malaysia: "Malezja",
   Mali: "Mali",
   Malta: "Malta",
   Mauritania: "Mauretania",
   Mauritius: "Mauritius",
   Mexico: "Meksyk",
   Moldova: "Mołdawia",
   Monaco: "Monako",
   Mongolia: "Mongolia",
   Morocco: "Maroko",
   Mozambique: "Mozambik",
   Namibia: "Namibia",
   Nepal: "Nepal",
   Netherlands: "Holandia",
   'New Zealand': "Nowa Zelandia",
   Nicaragua: "Nikaragua",
   Niger: "Niger",
   Nigeria: "Nigeria",
   'Korea Republic': "Korea Południowa",
   Norway: "Norwegia",
   'Northern Ireland': "Irlandia Północna",
   Oman: "Oman",
   Pakistan: "Pakistan",
   Panama: "Panama",
   Paraguay: "Paragwaj",
   Peru: "Peru",
   Philippines: "Filipiny",
   Poland: "Polska",
   Portugal: "Portugalia",
   Qatar: "Katar",
   Romania: "Rumunia",
   'Republic of Ireland': "Irlandia",
   Russia: "Rosja",
   Rwanda: "Rwanda",
   Scotland: "Szkocja",
   Senegal: "Senegal",
   Seychelles: "Seszele",
   Singapore: "Singapur",
   Slovakia: "Słowacja",
   Slovenia: "Słowenia",
   Somalia: "Somalia",
   'South Africa': "Republika Południowej Afryki",
   Spain: "Hiszpania",
   Sudan: "Sudan",
   Suriname: "Surinam",
   Sweden: "Szwecja",
   Switzerland: "Szwajcaria",
   Syria: "Syria",
   Taiwan: "Tajwan",
   Tajikistan: "Tadżykistan",
   Tanzania: "Tanzania",
   Thailand: "Tajlandia",
   Togo: "Togo",
   Tunisia: "Tunezja",
   Turkey: "Turcja",
   Turkmenistan: "Turkmenistan",
   Uganda: "Uganda",
   Ukraine: "Ukraina",
   'United States': "Stany Zjednoczone",
   Uruguay: "Urugwaj",
   Uzbekistan: "Uzbekistan",
   Vanuatu: "Vanuatu",
   Venezuela: "Wenezuela",
   Vietnam: "Wietnam",
   Wales: "Walia",
   Yemen: "Jemen",
   Zambia: "Zambia",
   Zimbabwe: "Zimbabwe"
}

export const nationalityTranslator = (string) => {
   const findNationality = countries[string]
   const finalNationality = findNationality === undefined ? string : findNationality;
   return finalNationality
}
